/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mikel
 */
public class proteccionDatos extends javax.swing.JFrame {

    /**
     * Creates new form ProtecionDatos
     */
    public proteccionDatos() {
        initComponents();
        setLocationRelativeTo(null);
        pDatos.setText(
               "1. Los datos de carácter personal sólo se podrán recoger para su tratamiento" +
                "así como someterlos a dicho tratamiento, cuando sean adecuados, pertinentes y" +
                "no excesivos en relación con el ámbito y las finalidades determinadas," +
                "explícitas y legítimas para las que se hayan obtenido." +
               "\n\n2. Los datos de carácter personal objeto de tratamiento" +
                "no podrán usarse para finalidades incompatibles con aquellas para las que los" +
                "datos hubieran sido recogidos. No se considerará incompatible el tratamiento posterior" +
                "de éstos con fines históricos, estadísticos o científicos." +
               "\n\n3. Los datos de carácter personal serán exactos y puestos al día de forma que respondan" +
                "con veracidad a la situación actual del afectado." +
               "\n\n4. Si los datos de carácter personal registrados resultaran ser inexactos," +
                "en todo o en parte, o incompletos, serán cancelados y sustituidos de oficio" +
                "por los correspondientes datos rectificados o completados, sin perjuicio de las facultades" +
                "que a los afectados reconoce el artículo 16." +
               "\n\n5. Los datos de carácter personal serán cancelados cuando hayan dejado" +
                "de ser necesarios o pertinentes para la finalidad para la cual hubieran sido recabados o registrados." +
                "No serán conservados en forma que permita la identificación del interesado" +
                "durante un período superior al necesario para los fines en base a" +
                "los cuales hubieran sido recabados o registrados." +
                "Reglamentariamente se determinará el procedimiento por el que, por excepción, atendidos" +
                "los valores históricos, estadísticos o científicos de acuerdo con la legislación específica," +
                "se decida el mantenimiento íntegro de determinados datos." +
               "\n\n6. Los datos de carácter personal serán almacenados de forma" +
                "que permitan el ejercicio del derecho de acceso, salvo que sean legalmente cancelados." +
               "\n\n7. Se prohíbe la recogida de datos por medios fraudulentos, desleales o ilícitos."
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        pDatos = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pDatos.setEditable(false);
        jScrollPane2.setViewportView(pDatos);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        jLabel1.setText("Protecion de Datos Personales:");

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bSalir)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
       controladorV.ProtecionDatosinscripcion();
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proteccionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proteccionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proteccionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proteccionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proteccionDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalir;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane pDatos;
    // End of variables declaration//GEN-END:variables
}
