-- MySQL Script generated by MySQL Workbench
-- Tue May  5 12:51:44 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `idProv` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Municipio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idProv` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `fk_Municipio_Provincia_idx` (`idProv` ASC),
  CONSTRAINT `fk_Municipio_Provincia`
    FOREIGN KEY (`idProv`)
    REFERENCES `mydb`.`Provincia` (`idProv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Calle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `idCalle` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idMunicipio` INT NOT NULL,
  PRIMARY KEY (`idCalle`),
  INDEX `fk_Calle_Municipio1_idx` (`idMunicipio` ASC),
  CONSTRAINT `fk_Calle_Municipio1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vivienda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda` (
  `idVivienda` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL DEFAULT 'S/N',
  `piso` VARCHAR(3) NULL,
  `letra` VARCHAR(1) NULL,
  `mano` VARCHAR(10) NULL,
  PRIMARY KEY (`idVivienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Direcccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Direcccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Direcccion` (
  `idCalle` INT NOT NULL,
  `idVivienda` INT NOT NULL,
  `cp` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idCalle`, `idVivienda`),
  INDEX `fk_Calle_has_Vivienda_Vivienda1_idx` (`idVivienda` ASC),
  INDEX `fk_Calle_has_Vivienda_Calle1_idx` (`idCalle` ASC),
  CONSTRAINT `fk_Calle_has_Vivienda_Calle1`
    FOREIGN KEY (`idCalle`)
    REFERENCES `mydb`.`Calle` (`idCalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calle_has_Vivienda_Vivienda1`
    FOREIGN KEY (`idVivienda`)
    REFERENCES `mydb`.`Vivienda` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CodigoPostal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CodigoPostal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CodigoPostal` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Centro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Centro` (
  `idCentro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(1) NOT NULL,
  `idProv` INT NOT NULL,
  PRIMARY KEY (`idCentro`),
  INDEX `fk_Centro_Provincia1_idx` (`idProv` ASC),
  CONSTRAINT `fk_Centro_Provincia1`
    FOREIGN KEY (`idProv`)
    REFERENCES `mydb`.`Provincia` (`idProv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menor` (
  `codMenor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ape1` VARCHAR(45) NOT NULL,
  `ape2` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(9) NULL,
  `fechaNac` DATE NOT NULL,
  `discapacidad` VARCHAR(45) NOT NULL,
  `idCalle` INT NOT NULL,
  `idVivienda` INT NOT NULL,
  `idCentro` INT NOT NULL,
  PRIMARY KEY (`codMenor`),
  INDEX `fk_Menor_Direcccion1_idx` (`idCalle` ASC, `idVivienda` ASC),
  INDEX `fk_Menor_Centro1_idx` (`idCentro` ASC),
  CONSTRAINT `fk_Menor_Direcccion1`
    FOREIGN KEY (`idCalle` , `idVivienda`)
    REFERENCES `mydb`.`Direcccion` (`idCalle` , `idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menor_Centro1`
    FOREIGN KEY (`idCentro`)
    REFERENCES `mydb`.`Centro` (`idCentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tutor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tutor` (
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ape1` VARCHAR(45) NOT NULL,
  `ape2` VARCHAR(45) NOT NULL,
  `tlf1` VARCHAR(45) NOT NULL,
  `tlf2` VARCHAR(45) NULL,
  `tlf3` VARCHAR(45) NULL,
  `tlf4` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sorteo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sorteo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sorteo` (
  `idSorteo` INT NOT NULL AUTO_INCREMENT,
  `diaIninio` DATE NOT NULL,
  `diaFin` DATE NOT NULL,
  `diaSorteo` DATE NOT NULL,
  PRIMARY KEY (`idSorteo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Solicitud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Solicitud` (
  `nSolicitud` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` TIME(9) NULL,
  `idSorteo` INT NOT NULL,
  PRIMARY KEY (`nSolicitud`),
  INDEX `fk_Solicitud_Sorteo1_idx` (`idSorteo` ASC),
  CONSTRAINT `fk_Solicitud_Sorteo1`
    FOREIGN KEY (`idSorteo`)
    REFERENCES `mydb`.`Sorteo` (`idSorteo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inscripcion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `idIns` INT NOT NULL AUTO_INCREMENT,
  `nSolicitud` INT NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `codMenor` INT NOT NULL,
  PRIMARY KEY (`idIns`),
  INDEX `fk_Inscripcion_Tutor1_idx` (`dni` ASC),
  INDEX `fk_Inscripcion_Menor1_idx` (`codMenor` ASC),
  CONSTRAINT `fk_Inscripcion_Solicitud1`
    FOREIGN KEY (`nSolicitud`)
    REFERENCES `mydb`.`Solicitud` (`nSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Tutor1`
    FOREIGN KEY (`dni`)
    REFERENCES `mydb`.`Tutor` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Menor1`
    FOREIGN KEY (`codMenor`)
    REFERENCES `mydb`.`Menor` (`codMenor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
